// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwsccottnqsigsqkqejn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3c2Njb3R0bnFzaWdzcWtxZWpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjQ2ODYsImV4cCI6MjA3MDUwMDY4Nn0.QywzhmG4mLaGbrj2kYXV1ol2GrKO9KxbFk0AFW_De10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});